AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Bathroom monitoring

Parameters:
  StageName:
    Type: String
    Default: dev


Globals:
  Function:
    Environment:
      Variables:
        STAGE: !Ref StageName

Resources:
  ### API REST
  ResourcesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ResourcesApi-${AWS::StackName}
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  ### Lambdas
  UpdateBathroomFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs14.x
      CodeUri: dist/src/apps/backend/lambdas/bathrooms/Update
      Handler: UpdateBathroom.handler
      Layers:
        - !Ref SharedLayer
        - !Ref BathroomsLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref BathroomsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BathroomsTable
      Events:
        PutExam:
          Type: Api
          Properties:
            RestApiId: !Ref ResourcesApi
            Path: /bathrooms/{id}
            Method: PUT
  
  FindBathroomFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs14.x
      CodeUri: dist/src/apps/backend/lambdas/bathrooms/Find
      Handler: FindBathroom.handler
      Layers:
        - !Ref SharedLayer
        - !Ref BathroomsLayer
      Environment:
        Variables:
          TABLE_NAME: !Ref BathroomsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BathroomsTable
      Events:
        PutExam:
          Type: Api
          Properties:
            RestApiId: !Ref ResourcesApi
            Path: /bathrooms
            Method: GET

  ### DynamoDB
  BathroomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-bathrooms
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH 
        - AttributeName: SK
          KeyType: RANGE 
      BillingMode: PAY_PER_REQUEST
  
  ### Layer
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-shared-module
      Description: Shared library
      ContentUri: ./dist/layers/shared
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: "MIT"
      RetentionPolicy: Delete

  BathroomsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-bathrooms-module
      Description: Bathrooms library
      ContentUri: ./dist/layers/bathrooms
      CompatibleRuntimes:
        - nodejs14.x
      LicenseInfo: "MIT"
      RetentionPolicy: Delete

Outputs:
  StageName:
    Description: "Stage"
    Value: !Ref StageName

  APIURL:
    Value: !Sub https://${ResourcesApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}


